### ISSUE TITLE
possible to clean the output of metalsmith-less 

### ISSUE THREAD

**Issue by nikmartin** [aymericbeaumet/metalsmith-clean-css#2]
my metalsmith source css is less, and is compiled into css during the build process. Is it possible to compress the contents of the css that has been output by the previous less plugin? The example shows looking for files with .css extension, but my css is only in the metalsmith output buffer, not in the source dir

**Comment by nikmartin** [comment]
nevermind, i guess i should have just tried it first :disappointed:

**Comment by wdmtech** [comment]
Just for anyone wondering about this like I was - if you omit the `files` attribute, this will clean any CSS file in the output buffer

**Comment by aymericbeaumet** [comment]
For anyone reaching this issue: the default value for `files` is `**/*.css`.

You can find out more in the [documentation](https://github.com/aymericbeaumet/metalsmith-clean-css#files).
