### ISSUE TITLE
clean css as a peer dependency?

### ISSUE THREAD

**Issue by vvo** [aymericbeaumet/metalsmith-clean-css#6]
Hi! Since this metalsmith plugin wraps clean-css, maybe we could put clean-css as a peer dependency to allow users to upgrade it without you having to upgrade your own lib? I am looking at using your plugin but wanted to ask that.

I can do the PR :)

**Comment by aymericbeaumet** [comment]
Sounds reasonable to me. Though you would have to be careful regarding the [v4 breaking changes](https://github.com/jakubpawlowicz/clean-css#important-40-breaking-changes) as I suppose you'd like to leverage the peer dependencies to bump the clean-css version :)
